# testbench
test_top_gate.v
../hdl/rom.v
../hdl/ram.v
../hdl/cache_ram.v
../hdl/dcache_ram.v
../hdl/uart1.v
../hdl/transmitter1.v
../hdl/receiver1.v

# netlist generated by Design Compiler
../../SYN/netlist/riscv_top_top_syn.v

# Logic Gate models
-v /usr/cadtool/GPDK45/gsclib045_svt_v4.4/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+GATESIM
+access+r
