../hdl/riscv_def.v
../hdl/riscv_alu.v
../hdl/riscv_exe_stage.v
../hdl/riscv_exe_decoder.v
../hdl/riscv_pc_stage.v
../hdl/riscv_skid_buffer.v
../hdl/riscv_fetch_stage.v
../hdl/riscv_decoder.v
../hdl/riscv_decode_stage.v
../hdl/riscv_instruction_queue.v
../hdl/riscv_pipeline_controller.v
../hdl/riscv_regfile.v
../hdl/riscv_issue_solver.v
../hdl/riscv_lsu.v
../hdl/riscv_mul.v
../hdl/riscv_div.v
../hdl/riscv_csr_handler.v
../hdl/riscv_csr_regfile.v
../hdl/riscv_core.v

../hdl/riscv_data_bus.v
../hdl/riscv_icache.v
../hdl/riscv_dcache.v
../hdl/uart.v
../hdl/transmitter.v
../hdl/receiver.v
../hdl/riscv_top.v
../hdl/riscv_top_top.v
../hdl/uart1.v
../hdl/transmitter1.v
../hdl/receiver1.v

../hdl/riscv_debug.v

../hdl/rom.v
../hdl/ram.v
../hdl/cache_ram.v
../hdl/dcache_ram.v
./test_top.v
